name: Branch Pruning

on:
  schedule:
    - cron: "0 2 * * *" # runs everyday at 2am

jobs:
  prune-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Prune Branches
        uses: peter-evans/branch-cleanup-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-until-stale: 30
          excluded-branches: main
